// Generated by Temporal Workflow Explorer. Do not edit.

import type { PaymentProfile, ProfileReceipt } from '../../src/activities/profile-activities';

/** Source: src/workflows/payload-workflow.ts:10 [confidence: exact] */
export declare function payloadWorkflow(profile: PaymentProfile): Promise<ProfileReceipt>;

/** Activity names referenced by this Workflow. */
export type PayloadWorkflowActivityName = 'storeProfile';
/** Implementation: src/activities/profile-activities.ts:12 [confidence: exact] */
