// Generated by Temporal Workflow Explorer. Do not edit.

import type { ChargeInput, TryFinallyResult } from '../../src/activities/charge-activities';

/** Source: src/workflows/charge-workflow.ts:16 [confidence: exact] */
export declare function chargeWorkflow(input: ChargeInput): Promise<TryFinallyResult>;

/** Activity names referenced by this Workflow. */
export type ChargeWorkflowActivityName = 'chargeAccount' | 'releaseLock';
/** Implementation: src/activities/charge-activities.ts:18 [confidence: exact] */
/** Implementation: src/activities/charge-activities.ts:22 [confidence: exact] */
