// Generated by Temporal Workflow Explorer. Do not edit.

import type { OrderInput, OrderResult } from '../../src/activities/order-activities';

/** Source: src/workflows/basic-order-workflow.ts:16 [confidence: exact] */
export declare function basicOrderWorkflow(input: OrderInput): Promise<OrderResult>;

/** Activity names referenced by this Workflow. */
export type BasicOrderWorkflowActivityName = 'chargeCard' | 'shipOrder' | 'validateOrder';
/** Implementation: src/activities/order-activities.ts:33 [confidence: exact] */
/** Implementation: src/activities/order-activities.ts:39 [confidence: exact] */
/** Implementation: src/activities/order-activities.ts:26 [confidence: exact] */
