// Generated by Temporal Workflow Explorer. Do not edit.

import type { OrchestrationInput, OrchestrationResult } from '../../src/activities/orchestration-activities';

/** Source: src/workflows/orchestration-workflow.ts:22 [confidence: exact] */
export declare function orchestrationWorkflow(input: OrchestrationInput): Promise<OrchestrationResult>;

/** Activity names referenced by this Workflow. */
export type OrchestrationWorkflowActivityName = 'auditStage' | 'buildPlan' | 'compensateStage' | 'confirmStage' | 'reserveInventory' | 'reserveShipping';
/** Implementation: src/activities/orchestration-activities.ts:37 [confidence: exact] */
/** Implementation: src/activities/orchestration-activities.ts:20 [confidence: exact] */
/** Implementation: src/activities/orchestration-activities.ts:41 [confidence: exact] */
/** Implementation: src/activities/orchestration-activities.ts:32 [confidence: exact] */
/** Implementation: src/activities/orchestration-activities.ts:24 [confidence: exact] */
/** Implementation: src/activities/orchestration-activities.ts:28 [confidence: exact] */
