// Generated by Temporal Workflow Explorer. Do not edit.

import type { ReviewInput, ReviewResult } from '../../src/activities/approval-activities';

/** Source: src/workflows/review-workflow.ts:17 [confidence: exact] */
export declare function reviewWorkflow(input: ReviewInput): Promise<ReviewResult>;

/** Activity names referenced by this Workflow. */
export type ReviewWorkflowActivityName = 'autoApprove' | 'finalizeReview' | 'managerApproval' | 'seniorApproval';
/** Implementation: src/activities/approval-activities.ts:28 [confidence: exact] */
/** Implementation: src/activities/approval-activities.ts:32 [confidence: exact] */
/** Implementation: src/activities/approval-activities.ts:24 [confidence: exact] */
/** Implementation: src/activities/approval-activities.ts:20 [confidence: exact] */
