// Generated by Temporal Workflow Explorer. Do not edit.

import type { ScreeningInput, ScreeningResult } from '../../src/activities/screening-activities';

/** Source: src/workflows/screening-workflow.ts:18 [confidence: exact] */
export declare function screeningWorkflow(input: ScreeningInput): Promise<ScreeningResult>;

/** Activity names referenced by this Workflow. */
export type ScreeningWorkflowActivityName = 'checkCompliance' | 'checkInventory' | 'checkPricing';
/** Implementation: src/activities/screening-activities.ts:25 [confidence: exact] */
/** Implementation: src/activities/screening-activities.ts:17 [confidence: exact] */
/** Implementation: src/activities/screening-activities.ts:21 [confidence: exact] */
