// Generated by Temporal Workflow Explorer. Do not edit.

import type { DrainInput, DrainResult } from '../../src/activities/drain-activities';

/** Source: src/workflows/drain-workflow.ts:15 [confidence: exact] */
export declare function drainWorkflow(input: DrainInput): Promise<DrainResult>;

/** Activity names referenced by this Workflow. */
export type DrainWorkflowActivityName = 'drainOne';
/** Implementation: src/activities/drain-activities.ts:15 [confidence: exact] */
