// Generated by Temporal Workflow Explorer. Do not edit.

import type { BroadcastInput, BroadcastResult } from '../../src/activities/broadcast-activities';

/** Source: src/workflows/broadcast-workflow.ts:19 [confidence: exact] */
export declare function broadcastWorkflow(input: BroadcastInput): Promise<BroadcastResult>;

/** Activity names referenced by this Workflow. */
export type BroadcastWorkflowActivityName = 'deliverToChannel' | 'prepareBroadcast' | 'summarizeBroadcast';
/** Implementation: src/activities/broadcast-activities.ts:30 [confidence: exact] */
/** Implementation: src/activities/broadcast-activities.ts:26 [confidence: exact] */
/** Implementation: src/activities/broadcast-activities.ts:37 [confidence: exact] */
