// Generated by Temporal Workflow Explorer. Do not edit.

import type { LargeInput } from '../../src/activities/large-activities';

/** Source: src/workflows/large-workflow.ts:12 [confidence: exact] */
export declare function largeWorkflow(input: LargeInput): Promise<string[]>;

/** Source: src/workflows/large-workflow.ts:6 [confidence: exact] */
export declare const pauseSignal: import('@temporalio/workflow').SignalDefinition<[string]>;

/** Activity names referenced by this Workflow. */
export type LargeWorkflowActivityName = 'step00' | 'step01' | 'step02' | 'step03' | 'step04' | 'step05' | 'step06' | 'step07' | 'step08' | 'step09' | 'step10' | 'step11' | 'step12' | 'step13' | 'step14' | 'step15' | 'step16' | 'step17' | 'step18' | 'step19' | 'step20' | 'step21' | 'step22' | 'step23' | 'step24' | 'step25' | 'step26' | 'step27' | 'step28' | 'step29' | 'step30' | 'step31' | 'step32' | 'step33' | 'step34' | 'step35' | 'step36' | 'step37' | 'step38' | 'step39' | 'step40' | 'step41' | 'step42' | 'step43' | 'step44' | 'step45' | 'step46' | 'step47' | 'step48' | 'step49' | 'step50' | 'step51' | 'step52' | 'step53' | 'step54' | 'step55' | 'step56' | 'step57' | 'step58' | 'step59';
/** Implementation: src/activities/large-activities.ts:9 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:13 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:17 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:21 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:25 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:29 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:33 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:37 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:41 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:45 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:49 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:53 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:57 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:61 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:65 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:69 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:73 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:77 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:81 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:85 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:89 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:93 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:97 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:101 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:105 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:109 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:113 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:117 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:121 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:125 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:129 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:133 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:137 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:141 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:145 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:149 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:153 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:157 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:161 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:165 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:169 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:173 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:177 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:181 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:185 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:189 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:193 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:197 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:201 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:205 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:209 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:213 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:217 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:221 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:225 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:229 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:233 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:237 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:241 [confidence: exact] */
/** Implementation: src/activities/large-activities.ts:245 [confidence: exact] */
