// Generated by Temporal Workflow Explorer. Do not edit.

import type { DynamicInput, DynamicResult } from '../../src/activities/step-activities';

/** Source: src/workflows/dynamic-workflow.ts:12 [confidence: exact] */
export declare function dynamicWorkflow(input: DynamicInput): Promise<DynamicResult>;

/** Activity names referenced by this Workflow. */
export type DynamicWorkflowActivityName = 'archiveRequest';
/** Implementation: src/activities/step-activities.ts:19 [confidence: exact] */
