// Generated by Temporal Workflow Explorer. Do not edit.

import type { BookingInput, BookingResult } from '../../src/activities/booking-activities';

/** Source: src/workflows/booking-workflow.ts:17 [confidence: exact] */
export declare function bookingWorkflow(input: BookingInput): Promise<BookingResult>;

/** Activity names referenced by this Workflow. */
export type BookingWorkflowActivityName = 'recordFailure' | 'releaseHold' | 'reserveSeats';
/** Implementation: src/activities/booking-activities.ts:27 [confidence: exact] */
/** Implementation: src/activities/booking-activities.ts:31 [confidence: exact] */
/** Implementation: src/activities/booking-activities.ts:23 [confidence: exact] */
