// Generated by Temporal Workflow Explorer. Do not edit.

import type { RaceInput, RaceResult } from '../../src/activities/market-activities';

/** Source: src/workflows/race-workflow.ts:19 [confidence: exact] */
export declare function raceWorkflow(input: RaceInput): Promise<RaceResult>;

/** Activity names referenced by this Workflow. */
export type RaceWorkflowActivityName = 'fetchLivePrice' | 'recordQuote';
/** Implementation: src/activities/market-activities.ts:22 [confidence: exact] */
/** Implementation: src/activities/market-activities.ts:26 [confidence: exact] */
