// Generated by Temporal Workflow Explorer. Do not edit.

import type { IterationInput } from '../../src/activities/iteration-activities';

/** Source: src/workflows/continue-as-new-workflow.ts:10 [confidence: exact] */
export declare function continueAsNewWorkflow(input: IterationInput): Promise<string>;

/** Activity names referenced by this Workflow. */
export type ContinueAsNewWorkflowActivityName = 'recordIteration';
/** Implementation: src/activities/iteration-activities.ts:10 [confidence: exact] */
