// Generated by Temporal Workflow Explorer. Do not edit.

import type { ParallelResult, ReservationInput } from '../../src/activities/reservation-activities';

/** Source: src/workflows/parallel-workflow.ts:24 [confidence: exact] */
export declare function parallelWorkflow(input: ReservationInput): Promise<ParallelResult>;

/** Activity names referenced by this Workflow. */
export type ParallelWorkflowActivityName = 'confirmReservation' | 'reserveInventory' | 'reserveShipping' | 'validateRequest';
/** Implementation: src/activities/reservation-activities.ts:44 [confidence: exact] */
/** Implementation: src/activities/reservation-activities.ts:36 [confidence: exact] */
/** Implementation: src/activities/reservation-activities.ts:40 [confidence: exact] */
/** Implementation: src/activities/reservation-activities.ts:32 [confidence: exact] */
