// Generated by Temporal Workflow Explorer. Do not edit.

import type { ApprovalInput, ApprovalRecord, ApprovalResult } from '../../src/activities/approval-activities';

/** Source: src/workflows/approval-workflow.ts:16 [confidence: exact] */
export declare function approvalWorkflow(input: ApprovalInput): Promise<ApprovalResult>;

/** Source: src/workflows/approval-workflow.ts:10 [confidence: exact] */
export declare const approveSignal: import('@temporalio/workflow').SignalDefinition<[ApprovalRecord]>;

/** Activity names referenced by this Workflow. */
export type ApprovalWorkflowActivityName = 'recordApproval';
/** Implementation: src/activities/approval-activities.ts:19 [confidence: exact] */
