// Generated by Temporal Workflow Explorer. Do not edit.

import type { PollInput, PollResult } from '../../src/activities/poll-activities';

/** Source: src/workflows/poll-workflow.ts:15 [confidence: exact] */
export declare function pollWorkflow(input: PollInput): Promise<PollResult>;

/** Activity names referenced by this Workflow. */
export type PollWorkflowActivityName = 'pollStatus';
/** Implementation: src/activities/poll-activities.ts:16 [confidence: exact] */
