// Generated by Temporal Workflow Explorer. Do not edit.

import type { FlagInput, FlagResult } from '../../src/activities/flag-activities';

/** Source: src/workflows/flag-workflow.ts:16 [confidence: exact] */
export declare function flagWorkflow(input: FlagInput): Promise<FlagResult>;

/** Activity names referenced by this Workflow. */
export type FlagWorkflowActivityName = 'applyFlag';
/** Implementation: src/activities/flag-activities.ts:15 [confidence: exact] */
