// Generated by Temporal Workflow Explorer. Do not edit.

import type { AnyResult, RegionInput } from '../../src/activities/region-activities';

/** Source: src/workflows/region-workflow.ts:18 [confidence: exact] */
export declare function regionWorkflow(input: RegionInput): Promise<AnyResult>;

/** Activity names referenced by this Workflow. */
export type RegionWorkflowActivityName = 'queryFallbackRegion' | 'queryPrimaryRegion';
/** Implementation: src/activities/region-activities.ts:22 [confidence: exact] */
/** Implementation: src/activities/region-activities.ts:18 [confidence: exact] */
