// Generated by Temporal Workflow Explorer. Do not edit.

import type { BatchInput, BatchResult } from '../../src/activities/batch-activities';

/** Source: src/workflows/batch-workflow.ts:16 [confidence: exact] */
export declare function batchWorkflow(input: BatchInput): Promise<BatchResult>;

/** Activity names referenced by this Workflow. */
export type BatchWorkflowActivityName = 'processItem';
/** Implementation: src/activities/batch-activities.ts:17 [confidence: exact] */
