// Generated by Temporal Workflow Explorer. Do not edit.

import type { PatchedInput, PatchedResult } from '../../src/activities/charge-activities';

/** Source: src/workflows/patched-workflow.ts:10 [confidence: exact] */
export declare function patchedWorkflow(input: PatchedInput): Promise<PatchedResult>;

/** Activity names referenced by this Workflow. */
export type PatchedWorkflowActivityName = 'newCharge' | 'oldCharge';
/** Implementation: src/activities/charge-activities.ts:23 [confidence: exact] */
/** Implementation: src/activities/charge-activities.ts:16 [confidence: exact] */
