// Generated by Temporal Workflow Explorer. Do not edit.

import type { OrderStatus, QueryFixtureInput, QueryFixtureResult } from '../../src/activities/audit-activities';

/** Source: src/workflows/query-workflow.ts:25 [confidence: exact] */
export declare function queryWorkflow(input: QueryFixtureInput): Promise<QueryFixtureResult>;

/** Source: src/workflows/query-workflow.ts:19 [confidence: exact] */
export declare const completeSignal: import('@temporalio/workflow').SignalDefinition<[]>;
/** Source: src/workflows/query-workflow.ts:17 [confidence: exact] */
export declare const auditCountQuery: import('@temporalio/workflow').QueryDefinition<number, [string]>;
/** Source: src/workflows/query-workflow.ts:18 [confidence: exact] */
export declare const bumpQuery: import('@temporalio/workflow').QueryDefinition<number, []>;
/** Source: src/workflows/query-workflow.ts:16 [confidence: exact] */
export declare const statusQuery: import('@temporalio/workflow').QueryDefinition<OrderStatus, []>;

/** Activity names referenced by this Workflow. */
export type QueryWorkflowActivityName = 'recordAudit';
/** Implementation: src/activities/audit-activities.ts:17 [confidence: exact] */
