// Generated by Temporal Workflow Explorer. Do not edit.

import type { ParentInput, ParentResult } from '../../src/workflows/child-workflow-parent';

/** Source: src/workflows/child-workflow-parent.ts:37 [confidence: exact] */
export declare function childWorkflowParent(input: ParentInput): Promise<ParentResult>;
