// Generated by Temporal Workflow Explorer. Do not edit.

import type { ChildInput, ChildNotice } from '../../src/workflows/child-workflow-parent';

/** Source: src/workflows/child-workflow-parent.ts:31 [confidence: exact] */
export declare function releaseNotificationChild(input: ChildInput): Promise<ChildNotice>;
