// Generated by Temporal Workflow Explorer. Do not edit.

import type { ChildInput, ChildSummary } from '../../src/workflows/child-workflow-parent';

/** Source: src/workflows/child-workflow-parent.ts:25 [confidence: exact] */
export declare function reserveInventoryChild(input: ChildInput): Promise<ChildSummary>;
