// Generated by Temporal Workflow Explorer. Do not edit.

/** Source: src/workflows/unsafe-workflow.ts:22 [confidence: exact] */
export declare function unsafeWorkflow(input: string): Promise<string>;

/** Source: src/workflows/unsafe-workflow.ts:11 [confidence: exact] */
export declare const duplicatedSignal: import('@temporalio/workflow').SignalDefinition<[string]>;
/** Source: src/workflows/unsafe-workflow.ts:10 [confidence: exact] */
export declare const progressQuery: import('@temporalio/workflow').QueryDefinition<number, []>;

/** Activity names referenced by this Workflow. */
export type UnsafeWorkflowActivityName = 'unresolvedActivity';
/** Implementation unresolved [confidence: inferred] */
