// Generated by Temporal Workflow Explorer. Do not edit.

import type { RetryInput, RetryResult } from '../../src/activities/charge-activities';

/** Source: src/workflows/retry-workflow.ts:15 [confidence: exact] */
export declare function retryWorkflow(input: RetryInput): Promise<RetryResult>;

/** Activity names referenced by this Workflow. */
export type RetryWorkflowActivityName = 'flakyCharge';
/** Implementation: src/activities/charge-activities.ts:19 [confidence: exact] */
