// Generated by Temporal Workflow Explorer. Do not edit.

import type { RaceInput, RaceResult } from '../../src/activities/race-activities';

/** Source: src/workflows/timer-race-workflow.ts:12 [confidence: exact] */
export declare function timerRaceWorkflow(input: RaceInput): Promise<RaceResult>;

/** Source: src/workflows/timer-race-workflow.ts:6 [confidence: exact] */
export declare const approveSignal: import('@temporalio/workflow').SignalDefinition<[string]>;

/** Activity names referenced by this Workflow. */
export type TimerRaceWorkflowActivityName = 'notifyApproved' | 'notifyExpired';
/** Implementation: src/activities/race-activities.ts:15 [confidence: exact] */
/** Implementation: src/activities/race-activities.ts:21 [confidence: exact] */
