// Generated by Temporal Workflow Explorer. Do not edit.

import type { ShippingAddress, UpdateFixtureInput, UpdateFixtureResult } from '../../src/activities/address-activities';

/** Source: src/workflows/update-workflow.ts:23 [confidence: exact] */
export declare function updateWorkflow(input: UpdateFixtureInput): Promise<UpdateFixtureResult>;

/** Source: src/workflows/update-workflow.ts:17 [confidence: exact] */
export declare const explodeUpdate: import('@temporalio/workflow').UpdateDefinition<void, [string]>;
/** Source: src/workflows/update-workflow.ts:16 [confidence: exact] */
export declare const setAddressUpdate: import('@temporalio/workflow').UpdateDefinition<ShippingAddress, [ShippingAddress]>;

/** Activity names referenced by this Workflow. */
export type UpdateWorkflowActivityName = 'recordAddress';
/** Implementation: src/activities/address-activities.ts:21 [confidence: exact] */
