// Generated by Temporal Workflow Explorer. Do not edit.

import type { CancellationInput, CancellationResult } from '../../src/activities/resource-activities';

/** Source: src/workflows/cancellation-workflow.ts:10 [confidence: exact] */
export declare function cancellationWorkflow(input: CancellationInput): Promise<CancellationResult>;

/** Activity names referenced by this Workflow. */
export type CancellationWorkflowActivityName = 'releaseResources' | 'reserveResources' | 'useResources';
/** Implementation: src/activities/resource-activities.ts:28 [confidence: exact] */
/** Implementation: src/activities/resource-activities.ts:18 [confidence: exact] */
/** Implementation: src/activities/resource-activities.ts:24 [confidence: exact] */
