// Generated by Temporal Workflow Explorer. Do not edit.

import type { RoutingInput, RoutingResult } from '../../src/activities/fulfillment-activities';

/** Source: src/workflows/routing-workflow.ts:20 [confidence: exact] */
export declare function routingWorkflow(input: RoutingInput): Promise<RoutingResult>;

/** Activity names referenced by this Workflow. */
export type RoutingWorkflowActivityName = 'basicFulfillment' | 'premiumFulfillment' | 'recordRouting' | 'standardFulfillment';
/** Implementation: src/activities/fulfillment-activities.ts:29 [confidence: exact] */
/** Implementation: src/activities/fulfillment-activities.ts:21 [confidence: exact] */
/** Implementation: src/activities/fulfillment-activities.ts:33 [confidence: exact] */
/** Implementation: src/activities/fulfillment-activities.ts:25 [confidence: exact] */
